// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function FetchURLs() {
  return window['go']['main']['App']['FetchURLs']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}
