// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<void>;

export function FetchURLs():Promise<Array<main.URLItem>>;

export function InstallUpdate():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;
